// This file is automatically generated. Do not edit it directly.
import AsyncStorage from "@react-native-async-storage/async-storage";
import { createClient } from "@supabase/supabase-js";
import { AppState, Platform } from "react-native";

export const supabase = createClient(
  "https://fdddvxvmkeqyufdrvcbc.supabase.co",
  "sb_publishable_xImLeAhhXyoXYJJzJUeGtQ_XHvs3Xkf",
  {
    auth: {
      storage: Platform.OS !== "web" ? AsyncStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  },
);
// App state listener for Supabase
AppState.addEventListener("change", (state) => {
  if (state === "active") {
    supabase.auth.startAutoRefresh();
  } else {
    supabase.auth.stopAutoRefresh();
  }
});
